### ISSUE TITLE
preprocessed 3d data problem

### ISSUE THREAD

**Issue by qiqiApink** [zemingxie/MPI_INF_3DHP-on-VideoPose3D#3]
I obtained preprocessed data following your code and ran videopose3d with it. But it threw the following error information:
```
Loading dataset...
Preparing data...
Traceback (most recent call last):
  File "run_poseformer.py", line 77, in <module>
    pos_3d = world_to_camera(anim['positions'], R=cam['orientation'], t=cam['translation'])
  File "/mnt/lvdisk1/yqzhang/PoseFormer/common/camera.py", line 30, in world_to_camera
    return wrap(qrot, np.tile(Rt, (*X.shape[:-1], 1)), X - t) # Rotate and translate
AttributeError: 'list' object has no attribute 'shape'
```
Can you tell me how to solve this? Thanks!

**Comment by zemingxie** [comment]
You are not running my code on VideoPose3D but on PoseFormer. I modified within run.py file on how to handle mpi data. If you want to make it work on PoseFormer, you have to modify the run_poseformer.py file to handle mpi data. 
But since PoseFormer is built on VideoPose3D, it should have similar steps for preprocessing data. You could try this (it is how I modify run.py to handle mpi data), not guarantee it is going to work on PoserFormer though since I didn't test it:
- copy paste mpi_inf_3dhp_dataset.py in the common folder to your common folder if you haven't already done so.
- With in run_poseformer.py, after 
```
if args.dataset == 'h36m':  
    from common.h36m_dataset import Human36mDataset  
    dataset = Human36mDataset(dataset_path)
```
Add following code to loading dataset step:
```
elif args.dataset.startswith('mpi'):
    from common.mpi_inf_3dhp_dataset import MpiInf3dhpDataset
    dataset = MpiInf3dhpDataset(dataset_path)
```
- With in run_poseformer.py, modify 
```
for subject in dataset.subjects():
    for action in dataset[subject].keys():
        anim = dataset[subject][action]

        if 'positions' in anim:
            positions_3d = []
            for cam in anim['cameras']:
                pos_3d = world_to_camera(anim['positions'], R=cam['orientation'], t=cam['translation'])
                pos_3d[:, 1:] -= pos_3d[:, :1] # Remove global offset, but keep trajectory in first position
                positions_3d.append(pos_3d)
            anim['positions_3d'] = positions_3d
```
To:
```
if args.dataset.startswith('mpi'):
    for subject in dataset.subjects():
        for action in dataset[subject].keys():
            anim = dataset[subject][action]
		
            if 'positions' in anim:
                anim['positions_3d'] = anim['positions']
else:
    for subject in dataset.subjects():
        for action in dataset[subject].keys():
            anim = dataset[subject][action]
            
            if 'positions' in anim:
                positions_3d = []
                for cam in anim['cameras']:
                    pos_3d = world_to_camera(anim['positions'], R=cam['orientation'], t=cam['translation'])
                    pos_3d[:, 1:] -= pos_3d[:, :1] # Remove global offset, but keep trajectory in first position
                    positions_3d.append(pos_3d)
                anim['positions_3d'] = positions_3d
```

Those steps should help to correctly import mpi_inf_3dhp data. Good luck!

**Comment by qiqiApink** [comment]
So you have already transformed 3d pose from world to camera in preprocess right?

**Comment by zemingxie** [comment]
No, I did not. Mpi_inf_3dhp gives the camera coordinate directly. I simply parsed the data into correct format.

**Comment by qiqiApink** [comment]
Oh I see. That means you directly use camera coordinate pose data so it doesn't need to be transformed. Did I got it?

**Comment by zemingxie** [comment]
yeah

**Comment by qiqiApink** [comment]
Thanks for your excellent work and replies!
